---
  - name: Install Local System Prerequesits
    connection: local
    become: true
    Ansible:
      roles:
        - docker

  - name: Install Prerequesits for External Worker Nodes
    connection: stack
    become: true
    Ansible:
      roles:
        - docker