
- name: Install Local System Prerequesits
  hosts: localhost
  become: true
  roles:
    - docker-node

- name: Install Prerequesits for External Worker Nodes
  hosts: localhost
  connection: stack
  become: true
  roles:
    - docker-node
